python setup.py build
rmdir build\exe.win-amd64-3.7\lib\scipy /Q /S
rmdir build\exe.win-amd64-3.7\lib\distutlis /Q /S
rmdir build\exe.win-amd64-3.7\lib\setuptools /Q /S
rmdir build\exe.win-amd64-3.7\lib\test /Q /S
rmdir build\exe.win-amd64-3.7\lib\unittest /Q /S
rmdir build\exe.win-amd64-3.7\lib\win32com /Q /S
rmdir build\exe.win-amd64-3.7\lib\xmlrpc /Q /S
rmdir build\exe.win-amd64-3.7\lib\async_generator /Q /S
rmdir build\exe.win-amd64-3.7\lib\asyncio /Q /S
rmdir build\exe.win-amd64-3.7\lib\attr /Q /S
rmdir build\exe.win-amd64-3.7\lib\backcall /Q /S
rmdir build\exe.win-amd64-3.7\lib\cffi /Q /S
rmdir build\exe.win-amd64-3.7\lib\chardet /Q /S
rmdir build\exe.win-amd64-3.7\lib\charset_normalizer /Q /S
rmdir build\exe.win-amd64-3.7\lib\colorama /Q /S
rmdir build\exe.win-amd64-3.7\lib\concurrent /Q /S
rmdir build\exe.win-amd64-3.7\lib\cryptography /Q /S
rmdir build\exe.win-amd64-3.7\lib\ctypes /Q /S
rmdir build\exe.win-amd64-3.7\lib\curses /Q /S
rmdir build\exe.win-amd64-3.7\lib\defusedxml /Q /S
rmdir build\exe.win-amd64-3.7\lib\et_xmlfile /Q /S
rmdir build\exe.win-amd64-3.7\lib\h11 /Q /S
rmdir build\exe.win-amd64-3.7\lib\idna /Q /S
rmdir build\exe.win-amd64-3.7\lib\importlib_metadata /Q /S
rmdir build\exe.win-amd64-3.7\lib\ipykernel /Q /S
rmdir build\exe.win-amd64-3.7\lib\IPython /Q /S
rmdir build\exe.win-amd64-3.7\lib\ipython_genutils /Q /S
rmdir build\exe.win-amd64-3.7\lib\jedi /Q /S
rmdir build\exe.win-amd64-3.7\lib\jinja2 /Q /S
rmdir build\exe.win-amd64-3.7\lib\joblib /Q /S
rmdir build\exe.win-amd64-3.7\lib\jsonschema /Q /S
rmdir build\exe.win-amd64-3.7\lib\jupyter_client /Q /S
rmdir build\exe.win-amd64-3.7\lib\jupyter_core /Q /S
rmdir build\exe.win-amd64-3.7\lib\lib2to3 /Q /S
rmdir build\exe.win-amd64-3.7\lib\markupsafe /Q /S
rmdir build\exe.win-amd64-3.7\lib\multiprocessing /Q /S
rmdir build\exe.win-amd64-3.7\lib\nbconvert /Q /S
rmdir build\exe.win-amd64-3.7\lib\nbformat /Q /S
rmdir build\exe.win-amd64-3.7\lib\notebook /Q /S
rmdir build\exe.win-amd64-3.7\lib\openpyxl /Q /S
rmdir build\exe.win-amd64-3.7\lib\OpenSSL /Q /S
rmdir build\exe.win-amd64-3.7\lib\outcome /Q /S
rmdir build\exe.win-amd64-3.7\lib\parso /Q /S
rmdir build\exe.win-amd64-3.7\lib\PIL /Q /S
rmdir build\exe.win-amd64-3.7\lib\pkg_resources /Q /S
rmdir build\exe.win-amd64-3.7\lib\prompt_toolkit /Q /S
rmdir build\exe.win-amd64-3.7\lib\pycparser /Q /S
rmdir build\exe.win-amd64-3.7\lib\pydoc_data /Q /S
rmdir build\exe.win-amd64-3.7\lib\pygments /Q /S
rmdir build\exe.win-amd64-3.7\lib\pyrsistent /Q /S
rmdir build\exe.win-amd64-3.7\lib\pytza /Q /S
rmdir build\exe.win-amd64-3.7\lib\requests /Q /S
rmdir build\exe.win-amd64-3.7\lib\sklearn /Q /S
rmdir build\exe.win-amd64-3.7\lib\sniffio /Q /S
rmdir build\exe.win-amd64-3.7\lib\sortedcontainers /Q /S
rmdir build\exe.win-amd64-3.7\lib\sqlite3 /Q /S
rmdir build\exe.win-amd64-3.7\lib\testpath /Q /S
rmdir build\exe.win-amd64-3.7\lib\tornado /Q /S
rmdir build\exe.win-amd64-3.7\lib\traitlets /Q /S
rmdir build\exe.win-amd64-3.7\lib\trio /Q /S
rmdir build\exe.win-amd64-3.7\lib\trio_websocket /Q /S
rmdir build\exe.win-amd64-3.7\lib\wcwidth /Q /S
rmdir build\exe.win-amd64-3.7\lib\wsproto /Q /S
rmdir build\exe.win-amd64-3.7\lib\xlrd /Q /S
rmdir build\exe.win-amd64-3.7\lib\zmq /Q /S
cd build
ren exe.win-amd64-3.7 gorealyzer_Win10